### PR TITLE
 Updated Tilburg, added Deventer and Arnhem

### PR DESCRIPTION
**Pull request by hvdndool**

### CODE REVIEW

**Review by matthijskooijman — COMMENTED** [review]
@hvdndool, it seems that you moved 503 to Arnhem, but I think it is also still contained in the tilburg set. Is that intentional?

Also, according to some other administration, sensor 500 was also assigned to Naan Eldring, just like most other ones in the the tilburg set, so I suspect that one is still unused somewhere but should be assigned to tilburg as well?

@giplt, @tammoterhark, this PR introduces a new sensor set for Arnhem and Deventer, with respectively 2 and 1 sensors that (I assume) have been passed on from Tilburg. I suspect there is no active group there, just a few lone sensors, should we have a separate sensor set for those? Or maybe just list them in an "other" set with some comments maybe (or just omit them from all sets maybe)?

**Comment by hvdndool** [comment]
@matthijskooijman Thanks for spotting that. I removed 503 from the Tilburg set. It was one of two sensors that were built in Tilburg but moved to the Arnhem-region. A third sensor moved to Deventer. We are still updating our administration so I added 500 to the Tilburg set.

**Comment by tammoterhark** [comment]
I would put sensors in cities where we actively work with (Tilburg, Zeist, Utrecht, Bergen(N), ?) in their own set and the rest in "others". I am not sure if my list of cities "where we actively work with" is complete, though. @giplt: can you complete the list? Maybe this could also be something we actively promote on the front page of meetjestad.net.

**Comment by giplt** [comment]
I would say the list with Meet je Stad active communities at this moment is:

  * Amersfoort (Netherlands)
  * Bergen (Norway)
  * Tilburg (Netherlands)
  * Utrecht (Netherlands)

Various levels of collaboration take place in:

  * Enschede (Netherlands): KITT Engineering is developing the hardware
    platform, no active community however
  * Arba Minch (Ethiopia): Starting up group
  * Apeldoorn (Netherlands): Community that forked the Meet je Stad
    technology, but so far shares back little in the terms of data,
    knowledge or development.
  * Grubbenvorst (Netherlands): One-man community at Stichting de Parel
    focusing on air quality measurements and sharing data and knowledge
    on their own platform
  * Zeist (Netherlands): Two-man community focusing on air quality
    measurements and sharing data and knowledge on their own platform

**Comment by JanRoem** [comment]
@hvdndool I am from city Arnhem and got my sensor from workshop Tilburg. # 415.
I am member of Luchtwachters Arnhem (Netherlands). 
My sensor is working. 
I have also a  Luftdaten.info sensorkit home made working.

**Comment by matthijskooijman** [comment]
W00ps, took a bit long to finalize this. Anyway, it's merged now, should be live on the website as well. @hvdndool, thanks!

**Pull request merged**
