### PR TITLE
Fix for measurement with a value of zero missing from json

### PR DESCRIPTION
**Pull request by bergrans**
This measurement (e.g. temperature = 0.0) did not show in json.

### CODE REVIEW

**Review by matthijskooijman — APPROVED** [review]
Looks good to me, thanks!

**Comment by bergrans** [comment]
This might have caused some unforeseen side effect. Since the json seems no longer valid, longitude and latitude values are  empty in some cases.

`{"row": 14,"id":504,"timestamp":"2021-04-23 18:25:32","firmware_version":2,"longitude":,"latitude":,"temperature":13.375,"humidity":56.625,"supply":3.3,"firmware_version":2},`

**Comment by matthijskooijman** [comment]
Good point, thanks. I added 7e989a874e7c8ac838931a10f6cd925e7686bcd7 to fix this. Could you check if this solves the issue for the export you were doing?

I also noticed that the date picker refused to allow dates > 2020, which I fixed in 7e989a874e7c8ac838931a10f6cd925e7686bcd7.

**Comment by bergrans** [comment]
Seems to work fine, for the [dashboard](http://www.bergrans.com/mjs-utrecht/) I made. Thanks!

**Pull request merged**
